name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Add-on configuration
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run add-on linter
        uses: frenck/action-app-linter@v2
        with:
          path: "./tellybox"
